[tool.black]
line-length = 88
target-version = ['py310']

[tool.pyright]
include = ["app", "tests", "scripts"]
exclude = ["**/__pycache__", ".venv"]
typeCheckingMode = "basic"
reportMissingImports = "warning"
reportMissingTypeStubs = "none"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.bandit]
skips = ["B101"]